stages:
  extract_text:
    cmd: python scripts/extract_text.py data/raw/pdfs data/extracted/text
    deps:
    - data/raw/pdfs
    - scripts/extract_text.py
    outs:
    - data/extracted/text
  extract_entities:
    cmd: python scripts/extract_entities.py data/extracted/text data/extracted/json_ner
      --model_name dslim/bert-base-NER
    deps:
    - data/extracted/text
    - scripts/extract_entities.py
    outs:
    - data/extracted/json_ner
  extract_people:
    cmd: python scripts/extract_people.py data/extracted/json_ner data/extracted/people/people.csv
    deps:
    - data/extracted/json_ner
    - scripts/extract_people.py
    outs:
    - data/extracted/people/people.csv
